version: '3.8'

services:
  mdbook:
    container_name: mdbook
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./book:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'