site_name: docs
#site_url: https://mkdocs.example.com/

docs_dir: docs
site_dir: /site

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized:
      type: custom
      custom_format: "%c"
      timezone: America/Toronto
      fallback_to_build_date: true
      enable_creation_date: true
      enable_git_follow: true