[book]
authors = []
language = "en"
multilingual = false
src = "src"

[output.html.fold]
enable = true

[output.html]
no-section-label = true
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
default-theme = "mocha"
preferred-dark-theme = "mocha"

[output.html.playground]
copyable = true          # include the copy button for copying code snippets
